// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.Models;

public partial class StudentDetailTbl_LINQ_
{
    public int Student_Id { get; set; }

    public string Address { get; set; }

    public string Contact_Number { get; set; }

    public string Course { get; set; }

    public DateTime Create_Time_Stamp { get; set; }

    public string DOB { get; set; }

    public string Email { get; set; }

    public string Gender { get; set; }

    public string Student_Name { get; set; }

    public DateTime Update_Time_Stamp { get; set; }

    public bool Is_Mathmatics { get; set; }

    public bool Is_English { get; set; }

    public bool Is_Chemistry { get; set; }

    public bool Is_Physics { get; set; }

    public bool Is_Biology { get; set; }

    public bool Is_Deleted { get; set; }
}